name: flutter_initicon
description: "Initicon are used to show the initials of the name of users who do not have an avatar or profile image."
version: 2.0.0
homepage: https://github.com/lrferreiro/flutter_initicon

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
